version: '3.9'

services:
  oracle:
    image: truevoly/oracle-12c
    container_name: bookstore-oracle-12c
    ports:
      - "1521:1521"
      - "8100:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=false
      - ORACLE_ENABLE_XDB=true
      - ORACLE_PASSWORD=oracle
    volumes:
      - ./oracle:/u01/app/oracle

